# Use the following code for the questions below:

In [3]:
import numpy as np

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

## ex 1. How many negative numbers are there?

In [5]:
neg_mask = a < 0 
neg_mask

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [7]:
len(a[neg_mask])

4

## ex 2. How many positive numbers are there?

In [8]:
pos_mask = a > 0 
pos_mask

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True, False])

In [9]:
len(a[pos_mask])

5

## ex 3. How many even positive numbers are there?

In [55]:
even_mask= a%2 == 0
a[even_mask]
a[pos_even_mask]

array([ 4, 10, 12,  0,  0,  0])

In [49]:
pos_even_mask = (a >= 0) & (a%2 == 0)
len(a[pos_even_mask])

6

## ex 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [62]:
b = a+3

In [63]:
b

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [68]:
bpem= (b>=0) & (b%2==0)
b[bpem]
len(b[bpem])

3

## ex 5. If you squared each number, what would the new mean and standard deviation be?

In [69]:
squared = a **2
squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [74]:
print(squared.mean())
print(squared.std())

74.0
144.0243035046516


## ex 6. A common statistical operation on a dataset is centering. 
This means to adjust the data such that the mean of the data is 0. 
This is done by subtracting the mean from each data point. 
Center the data set. 
See this link for more on centering.

In [75]:
a.mean()

3.0

In [78]:
centered = a - a.mean()
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [79]:
centered.mean()

0.0

## ex 7. Calculate the z-score for each data point. Recall that the z-score is given by:

In [80]:
za= ((a) - (a.mean())) / (a.std())
za

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## ex 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

### Setup 1

In [81]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [94]:
sum_of_a = sum(a)
sum_of_a

55

#### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [95]:
min_of_a = min(a)
min_of_a

1

#### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [96]:
max_of_a = max(a)
max_of_a

10

#### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [98]:
mean_of_a = (sum(a) / len(a))
mean_of_a

5.5

#### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [88]:
product_of_a = 1

for n in a:
    product_of_a *= n
    
product_of_a

3628800

#### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [89]:
squares_of_a = []

for n in a:

    squares_of_a.append(n**2)

squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [90]:
odds_in_a = []

for n in a:

    if n%2 != 0:
        odds_in_a.append(n)

odds_in_a

[1, 3, 5, 7, 9]

#### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [91]:
evens_in_a = []

for n in a:

    if n%2 == 0:
        evens_in_a.append(n)

evens_in_a

[2, 4, 6, 8, 10]

### Setup 2 -Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [101]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

#### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
**Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [ ]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)


In [103]:
array_b = np.array(b)
np.sum(array_b)

33

#### Exercise 2 - refactor the following to use numpy. 

In [ ]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [104]:
np.min(array_b)

3

#### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [ ]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [105]:
np.max(array_b)

8

#### Exercise 4 - refactor the following using numpy to find the mean of b

In [ ]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [106]:
np.mean(array_b)

5.5

#### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [ ]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [107]:
np.prod(array_b)

20160

#### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [ ]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [108]:
squared_b= array_b **2
squared_b

array([[ 9, 16, 25],
       [36, 49, 64]])

#### Exercise 7 - refactor using numpy to determine the odds_in_b

In [ ]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [111]:
odds_of_b = array_b %2 != 0
array_b[odds_of_b]

array([3, 5, 7])

####  Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [ ]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [112]:
array_b[~odds_of_b]

array([4, 6, 8])

### Setup 3

In [115]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

#### Exercise 1 - Find the min, max, sum, and product of c.

In [117]:
array_c = np.array(c)
array_c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
print('min', np.min(array_c))
print('max', np.max(array_c))
print('sum', np.sum(array_c))
print('prod', np.prod(array_c))

min 1
max 9
sum 45
prod 362880


#### Exercise 2 - Determine the standard deviation of c.

In [122]:
np.std(array_c)

2.581988897471611

#### Exercise 3 - Determine the variance of c.

In [126]:
array_c.var()

6.666666666666667

#### Exercise 4 - Print out the shape of the array c

In [128]:
array_c.shape

(3, 3)

#### Exercise 5 - Transpose c and print out transposed result.

In [132]:
trans_c = array_c.T

#### Exercise 6 - Get the dot product of the array c with c. 

In [130]:
np.dot(array_c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [140]:
trans_c_by_c = trans_c * c
np.sum(trans_c_by_c)

261

#### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [145]:
trans_c_by_c.prod()


131681894400

### Setup 4

In [146]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]


In [147]:
array_d = np.array(d)

#### Exercise 1 - Find the sine of all the numbers in d

In [148]:
np.sin(array_d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

#### Exercise 2 - Find the cosine of all the numbers in d

In [149]:
np.cos(array_d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

#### Exercise 3 - Find the tangent of all the numbers in d

In [150]:
np.tan(array_d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#### Exercise 4 - Find all the negative numbers in d

In [152]:
array_d_neg = array_d < 0
array_d[array_d_neg]

array([-90, -30, -45, -45])

#### Exercise 5 - Find all the positive numbers in d

In [153]:
array_d[~array_d_neg]

array([ 90,  30,  45,   0, 120, 180,  45, 270,  90,   0,  60,  45,  90,
       180])

#### Exercise 6 - Return an array of only the unique numbers in d.

In [155]:
np.unique(array_d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

#### Exercise 7 - Determine how many unique numbers there are in d.

In [156]:
len(np.unique(array_d))

11

#### Exercise 8 - Print out the shape of d.

In [160]:
array_d.shape

(3, 6)

#### Exercise 9 - Transpose and then print out the shape of d.

In [161]:
(array_d.T).shape

(6, 3)

#### Exercise 10 - Reshape d into an array of 9 x 2

In [166]:
np.reshape(array_d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])